Get image size from topic instead of rosparam (#19)
* Get image size from topic instead of rosparam

* Avoid attribute error

AttributeError: ImageUndistortion instance has no attribute '_captured_img_width'

* Get image size from topic instead of rosparam on depth estimation

* Fix merge error